APP          = MobileContactApplication 
WORKSPACE    = MobileContactApplication
CONFIG       = Debug 
SCHEME       = MobileContactApplication

# iMessage addresses list seperated with white space
# IMSG_LIST    = a_imessage_email@mac.com +86.18621800000 another_email@me.com

# Comment the following line if you prefer Bonjour Network
# BASE_URL     = http://ota.nsnotfound.com

# Your Mailgun mail list
EMAIL_LIST   = justin.yang2012@gmail.com 
EMAIL_DOMAIN = gmail.com

# Get API key from Keychain by item name "mailgun api key"
MAILGUN_API_KEY = $(shell security find-generic-password -l "mailgun api key" -gw)

# Your server with SSH access
SFTP_SERVER  = lexrus@nsnotfound.com
SFTP_PATH    = /var/www/ota
SFTP_PORT    = 22

# Share via Apple Bonjour Network
BASE_PORT    = 9966
BASE_URL    ?= http://$(shell scutil --get ComputerName).local:$(BASE_PORT)
