platform :ios, '6.0'
pod 'OHHTTPStubs', '~>2.0.0'
pod 'MJNIndexView', '~> 0.0.1'
pod 'DKLiveBlur', '~> 0.0.1'
pod 'WSCoachMarksView', '~> 0.2'
pod 'DAKeyboardControl', '~> 2.2.0'
pod 'SSDataKit', '~> 0.1.5'
pod 'FXBlurView', '~> 1.3.1'
pod 'TMCache', '~> 1.2.0'
pod 'RHAddressBook', '~> 1.0.2'
pod 'ReactiveCocoa', '~> 2.0'
pod 'RNThemeManager', '~> 0.1.0'
pod 'RSCategories', '~> 0.1'
pod 'KLSwitch', '~> 1.5'
pod 'UIImageViewModeScaleAspect', '~> 1.1'
pod 'FlipBoardNavigationController', '~> 1.0'
pod 'MCSwipeTableViewCell', '~> 1.1.1'
pod 'HTAutocompleteTextField', '~> 1.2.2'
pod "AFNetworking", "~> 2.0"
pod 'EAIntroView', '~> 2.6'
pod 'FLKAutoLayout', '~> 0.1'
pod 'RESideMenu', '~> 4.0'
pod 'Mantle'
pod 'PonyDebugger', '~>0.3.0'
